config/routes.rb
Rails.application.routes.draw do
  resources :products
  namespace :carts do
    resource :add, only: :create
    resource :reduce, only: :create
    resource :remove, only: :destroy
  end
  resource :checkout, only: :show

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  token      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_carts_on_token  (token) UNIQUE
#
class Cart < ApplicationRecord
  has_secure_token
	has_many :cart_items, dependent: :destroy

  def quantity
    cart_items.sum(&:quantity)
  end
end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id         :bigint           not null, primary key
#  quantity   :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cart_id    :bigint           not null
#  product_id :bigint           not null
#
# Indexes
#
#  index_cart_items_on_cart_id     (cart_id)
#  index_cart_items_on_product_id  (product_id)
#
# Foreign Keys
#
#  fk_rails_...  (cart_id => carts.id)
#  fk_rails_...  (product_id => products.id)
#
class CartItem < ApplicationRecord
  # since we are using this: target: dom_id(self, "quantity")
  # below, we need to include this include
  include ActionView::RecordIdentifier

  belongs_to :cart
  belongs_to :product

  after_create_commit do
    update_item_count
    update_total_price
  end

  after_update_commit do
    update_item_count
    update_total_price
    broadcast_replace_to cart, target: dom_id(self, "quantity"), partial: "carts/item_quantity", locals: { cart_item: self }
  end

  after_destroy_commit do
    broadcast_remove_to cart
    update_item_count
    update_total_price
  end

  def total_price
    PricingService.call(quantity: quantity.to_i, product: product)
  end

  private

  def update_total_price
    broadcast_replace_to cart,
                         target: "total_price",
                         partial: "carts/total_price",
                         locals: { current_cart: cart }
  end

  def update_item_count
    broadcast_replace_to cart,
                         target: "cart_count",
                         partial: "carts/item_count",
                         locals: { count: cart.quantity }
  end
end

app/models/discount.rb
# == Schema Information
#
# Table name: discounts
#
#  id          :bigint           not null, primary key
#  description :string
#  name        :string
#  rule_params :jsonb
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Discount < ApplicationRecord
  has_many :products
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :bigint           not null, primary key
#  name         :string
#  price        :decimal(8, 2)
#  product_code :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  discount_id  :integer
#
class Product < ApplicationRecord
  # validations
  validates :product_code, :name, :price, presence: true
  # associations
  has_many :cart_items, dependent: :destroy
  belongs_to :discount, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_cart
  def current_cart
    cart = Cart.find_or_create_by(token: cookies[:cart_token])
    cookies[:cart_token] ||= cart.token
    cart
  end
end

app/controllers/carts/adds_controller.rb
module Carts
  class AddsController < ApplicationController
    def create
      if product_found?
        cart_item = current_cart.cart_items.find_or_initialize_by(product_id: params[:product])
        cart_item.quantity += 1
        cart_item.save
      end
    end

    private

    def product_found?
      Product.exists?(params[:product])
    end
  end
end

app/controllers/carts/reduces_controller.rb
module Carts
  class ReducesController < ApplicationController
    def create
      if product_found?
        cart_item = current_cart.cart_items.find_or_initialize_by(product_id: params[:product])
        cart_item.quantity = [cart_item.quantity - 1, 1].max
        cart_item.save
      end
    end

    private

    def product_found?
      Product.exists?(params[:product])
    end
  end
end

app/controllers/carts/removes_controller.rb
module Carts
  class RemovesController < ApplicationController
    def destroy
      if product_found?
        cart_item = current_cart.cart_items.find_by(product_id: params[:product])
        cart_item.destroy
      end
    end

    private

    def product_found?
      Product.exists?(params[:product])
    end
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/_checkout_button.html.erb
<div class="mb-3">
  <%= link_to checkout_path, class: "btn btn-outline-dark" do %>
    <div class="badge bg-primary">
      <%= render "carts/item_count", count: current_cart.quantity %>
    </div>
    Checkout
  <% end %>
</div>

app/views/carts/_item_count.html.erb
<%= content_tag :div, count, id: "cart_count" %>

app/views/carts/_item_line.html.erb
<%= content_tag :div, class: "row mb-8 align-items-center", id: dom_id(cart_item) do %>
  <div class="col-12 col-md-9">
    <div class="d-flex justify-content-between">
      <div class="pe-2">
        <h3 class="mb-2 lead fw-bold"><%= cart_item.product.name %></h3>
      </div>
      <div>
        <span class="lead text-info fw-bold"><%= number_to_currency(cart_item.product.price) %></span>
        <%= button_to "remove",
          carts_remove_path, 
          class: "btn btn-danger",
          params: { product: cart_item.product },
          method: :delete %>
      </div>
    </div>
    <div class="d-flex align-items-center justify-content-between">
      <div></div>
      <div class="d-inline-flex align-items-center px-4 fw-bold text-secondary border rounded-2">
        <%= button_to "-", carts_reduce_path, params: { product: cart_item.product }, class: "btn px-0 py-2" %>
        <div class="form-control m-0 px-2 py-4 text-center text-md-end border-0">
          <%= render "carts/item_quantity", cart_item: cart_item %>
        </div>
        <%= button_to "+", carts_add_path, params: { product: cart_item.product }, class: "btn px-0 py-2" %>
      </div>
    </div>
  </div>
<% end %>

app/views/carts/_item_quantity.html.erb
<%= content_tag :span, cart_item.quantity, id: dom_id(cart_item, "quantity") %>

app/views/carts/_total_price.html.erb
<span class="fw-bold" id="total_price">
  <%= number_to_currency(current_cart.cart_items.sum(&:total_price)) %>
</span>

app/views/checkouts/show.html.erb
<%= turbo_stream_from current_cart %>
<div class="py-16 px-6 px-md-14 bg-white">
  <div class="d-flex mb-12 align-items-center">
    <h3 class="mb-0">Order summary</h3>
    <span class="flex-shrink-0 d-inline-flex ms-4 align-items-center justify-content-center rounded-circle bg-primary text-white" style="width: 32px; height: 32px;">
      <%= render "carts/item_count", count: current_cart.quantity %>
    </span>
  </div>
 <div class="mb-12 pb-16 border-bottom">
    <% current_cart.cart_items.each do |cart_item| %>
      <%= render "carts/item_line", cart_item: cart_item %>
    <% end %>
  </div>
  <div class="mb-12">
    <div class="mb-10">
      <div class="py-3 px-10 rounded-pill">
     		<div class="d-flex justify-content-between">
          <span class="lead fw-bold" data-config-id="row4">Total</span>
          <%= render "carts/total_price" %>
        </div>
      </div>
    </div>
  </div>

  <a class="btn btn-primary w-100 text-uppercase" href="#" data-config-id="primary-action">Confirm Order</a>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" data-config-id="brand">
      Shop
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="d-none d-lg-flex navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="nav-item me-4">
  <%= link_to "Home", root_path, class: 'nav-link' %>
</li>
<li class="nav-item me-4">
  <%= link_to "Products", products_path, class: 'nav-link' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmenitizTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= turbo_include_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body class='bg-light'>
    <div class="container bg-white border pb-3">
      <%= render 'layouts/navigation' %>
      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <%= content_tag :div, msg, class: "alert alert-danger", role: :alert %>
          <% else %>
          <%= content_tag :div, msg, class: "alert alert-primary", role: :alert %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_display.html.erb
<%= turbo_frame_tag "products_display" do %>
  <div class="row">
    <% products.each_slice(3) do |product_group| %>
      <% product_group.each do |product| %>
        <div class="col-12 col-md-6 col-lg-4">
          <div class="card mb-5">
            <div class="card-body">
              <h5 class="card-title">
                <%= product.name %><br>
                <%= number_to_currency(product.price) %>
              <h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <%= button_to "Add to Cart", carts_add_path, params: { product: product }, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/products/index.html.erb
<%= turbo_stream_from current_cart %>
<%= render "carts/checkout_button" %>

<div class="row">
	<div class="col-12 col-lg-3">
	</div>
	<div class="col-12 col-lg-9">
		<%= render "products/display", products: @products %>
	</div>
</div>